-- SEQUENCE, INDEX, SYNONYMS
---------------------------------------------------------------------------


1) SEQUENCES
OBEJTOS DO ORACLE FACILITAR PARA GERAÇÃO DA CHAVE PRIMÁRIA

SÃO INDEPENDENTES DAS TABLEAS
USAR A SEQUENCE EM UALQUER TABELA

CREATE SEQUENCE <NAME>
    INCREMENT BY <N>
     START WITH <VALOR INICIAL>
     MAX_VALUE
    MINVALUE
    CYCLE | NOCYCLE

SELECT * FROM USER_SEQUENCES

CREATE SEQUENCE SEQ_CUSTOMER
     INCREMENT BY 1
     START WITH 1
     MAXVALUE 999999
     CYCLE;

SELECT SEQ_CUSTOMER.NEXTVAL
       ,SEQ_CUSTOMER.CURRVAL
FROM DUAL;

INSERT...VALUES...SEQ_CUSTOMER.NEXTVAL

ALTER SEQUENCE

ALTER SEQUENCE

DROP SEQUENCE
-------------------------------------------------------------------------
2) INDICES
ACELERAR O RETORNO DA INSTRUÇÃO SELECT

CONSTRAINTS PRIMARY KEY, UNIQUE -> ORACLE CREATE INDEXES

CREATE INDEX <NAME> ON <TABLE> (COL1,COL2...)

DROP TABLE CUSTOMERS
CREATE TABLE CUSTOMERS
(
   ID INT,
   NAME VARCHAR2(10)
)
CREATE INDEX IX_CUSTOMERS ON CUSTOMERS(NAME)

SELECT * FROM USER_INDEXES WHERE INDEX_NAME='IX_CUSTOMERS'
-------------------------------------------------------------------------------------------------------

3)SYNONYM
ALIAS
APELIDO

SELECT * FROM HR.DEPARTMENTS 

CREATE SYNONYM  DEP FOR HR.DEPARTMENTS

SELECT * FROM DEP

DROP SYNONYM DEP