-- CONSTRINTS - OBJETOS DOS BANCOS DE DADOS QUE MANTEM A INTEGRIDADE - CONFIABILIDADE DOS DADOS
-------------------------------------------------------------------
NOT NULL
UNIQUE
PRIMARY KEY
FOREIGN KEY
CHECK
-------------------------------------------------------------------------------------
1) CONSTRAINT -  NOT NULL
AUSÊNCIA DE DADOS

CREATE TABLE CUSTOMERS
(
    ID INT NOT NULL,
    NAME VARCHAR2(50) NULL
)

INSERT INTO CUSTOMERS VALUES (1,'A');
INSERT INTO CUSTOMERS VALUES (2,NULL);
INSERT INTO CUSTOMERS VALUES (NULL,'A');

DROP TABLE CUSTOMERS

CREATE TABLE CUSTOMERS
(
    ID INT ,
    NAME VARCHAR2(50)
    CONSTRAINT CUST_NULL NULL
)
select * from user_constraints
DESC CUSTOMERS
-----------------------------------------------------------

2) UNIQUE
A DIFERENCA ENTE UNIQUE E < PK >  É QUE A PRIMEIRA ACEITA NULL E A SEGUNDA(PK) NÃO


CREATE TABLE CUSTOMERS
(
    ID INT UNIQUE,
    NAME VARCHAR2(50)
)

INSERT INTO CUSTOMERS VALUES(1,'A')
INSERT INTO CUSTOMERS VALUES(NULL,'A')
INSERT INTO CUSTOMERS VALUES(1,'B')
SELECT * FROM CUSTOMERS 
-- DROP TABLE CUSTOMERS
------------------------------------------------------------

3) PRIMARY KEY
DEVE SER ESPECIFICADA APÓS O MODELO DE DADOS.

CREATE TABLE CUSTOMERS
(
    ID INT PRIMARY KEY,
    NAME VARCHAR2(50)
)

CREATE TABLE CUSTOMERS
(
    ID INT CONSTRAINT PK_CUSTOMERS PRIMARY KEY,
    NAME VARCHAR2(50)
)

CREATE TABLE CUSTOMERS
(
    ID INT,
    NAME VARCHAR2(50),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY(ID)
)
 
INSERT INTO CUSTOMERS VALUES(1,'A')
INSERT INTO CUSTOMERS VALUES(NULL,'A')
INSERT INTO CUSTOMERS VALUES(1,'B')
SELECT * FROM CUSTOMERS 
-- DROP TABLE CUSTOMERS

---------------------------------------------------------------------------
4) FOREIGN KEY
CREATE TABLE CUSTOMERS
(
    ID INT,
    NAME VARCHAR2(50),
    LOCATION_ID INT,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY(ID),
    CONSTRAINT FK_CUSTOMERS FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
)

CREATE TABLE CUSTOMERS
(
    ID INT PRIMARY KEY,
    NAME VARCHAR2(50),
    LOCATION_ID INT,
    CONSTRAINT FK_CUSTOMERS FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
)

INSERT INTO CUSTOMERS VALUES (1,'A',1000)
INSERT INTO CUSTOMERS VALUES (1,'A',55)
SELECT * FROM LOCATIONS
----------------------------------------------------------------------------------------------------------------
5) CHECK
REGRAS DE NEGÓCIOS
RESTRIÇÕES

CREATE TABLE CUSTOMERS
(
        ID INT NOT NULL CHECK(ID>0),
        NAME VARCHAR2(50)
)

INSERT INTO CUSTOMERS VALUES(1,'A')
INSERT INTO CUSTOMERS VALUES(0,'A')

ALTER TABLE
DISABLE CONSTAINT...